/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ChatRoomGUI;

/**
 *
 * @author Abdullah
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JScrollPane();
        membersList = new javax.swing.JPanel();
        rightPanel = new javax.swing.JSplitPane();
        chatPanel = new javax.swing.JScrollPane();
        chatText = new javax.swing.JTextPane();
        messagePanel = new javax.swing.JPanel();
        messageInputPanel = new javax.swing.JScrollPane();
        messageInput = new javax.swing.JTextArea();
        messageSendButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Room");
        setMinimumSize(new java.awt.Dimension(600, 400));

        splitPane.setResizeWeight(0.3);
        splitPane.setOneTouchExpandable(true);

        membersList.setLayout(new javax.swing.BoxLayout(membersList, javax.swing.BoxLayout.Y_AXIS));
        leftPanel.setViewportView(membersList);

        splitPane.setLeftComponent(leftPanel);

        rightPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        rightPanel.setResizeWeight(0.8);

        chatText.setEditable(false);
        chatText.setText("Chat will be displayed here.");
        chatPanel.setViewportView(chatText);

        rightPanel.setTopComponent(chatPanel);

        messagePanel.setLayout(new javax.swing.BoxLayout(messagePanel, javax.swing.BoxLayout.X_AXIS));

        messageInput.setColumns(20);
        messageInput.setRows(5);
        messageInput.setText("Typle message here...");
        messageInputPanel.setViewportView(messageInput);

        messagePanel.add(messageInputPanel);

        messageSendButton.setText("Send");
        messagePanel.add(messageSendButton);

        rightPanel.setRightComponent(messagePanel);

        splitPane.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane chatPanel;
    public javax.swing.JTextPane chatText;
    private javax.swing.JScrollPane leftPanel;
    public javax.swing.JPanel membersList;
    public javax.swing.JTextArea messageInput;
    private javax.swing.JScrollPane messageInputPanel;
    private javax.swing.JPanel messagePanel;
    public javax.swing.JButton messageSendButton;
    private javax.swing.JSplitPane rightPanel;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
